name: Einführung in Data Science

on:
  push:
    paths:
      - bachelor/ds/**
  pull_request:
    paths:
      - bachelor/ds/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: pblan/matse-spicker/.github/workflows/compile.yml@main
    with:
       spicker-handle: ds
       spicker-fullname: Einführung in Data Science