name: Numerik 1 (Test)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - num1/**
  pull_request:
    branches: [ main ]
    paths:
      - num1/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: ./.github/actions/compile.yml
      with:
        spicker-handle: num1
        spicker-path: / 
        spicker-fullname: Numerik 1
