name: Numerik 1

on:
  push:
    paths:
      - bachelor/num1/**
  pull_request:
    paths:
      - bachelor/num1/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: pblan/matse-spicker/.github/workflows/compile.yml@main
    with:
       spicker-handle: num1
       spicker-fullname: Numerik 1
       spicker-path: bachelor/num1