name: Paralelle Rechnerarchitekturen

on:
  push:
    branches:
      - main
      - development
    paths:
      - master/para/**
  pull_request:
    branches:
      - main
      - development
    paths:
      - master/para/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: pblan/matse-spicker/.github/workflows/compile.yml@main
    with:
       spicker-handle: para
       spicker-fullname: Parallele Rechnerarchitekturen