name: Stochastik

on:
  push:
    branches:
      - main
      - development
    paths:
      - bachelor/sto/**
  pull_request:
    branches:
      - main
      - development
    paths:
      - bachelor/sto/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: pblan/matse-spicker/.github/workflows/compile.yml@main
    with:
       spicker-handle: sto
       spicker-fullname: Stochastik