name: Softwaretechnik

on:
  push:
    branches:
      - main
      - development
    paths:
      - bachelor/swt/**
  pull_request:
    branches:
      - main
      - development
    paths:
      - bachelor/swt/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile:
    uses: pblan/matse-spicker/.github/workflows/compile.yml@main
    with:
       spicker-handle: swt
       spicker-fullname: Softwaretechnik